// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/res_server_list.proto

package com.insping.libra.proto;

public final class ResServerList {
  private ResServerList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerListDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ServerListData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    java.util.List<RoleData>
        getRolesList();
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    RoleData getRoles(int index);
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    int getRolesCount();
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    java.util.List<? extends RoleDataOrBuilder>
        getRolesOrBuilderList();
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    RoleDataOrBuilder getRolesOrBuilder(
            int index);

    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    java.util.List<ServerData>
        getServerListList();
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    ServerData getServerList(int index);
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    int getServerListCount();
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    java.util.List<? extends ServerDataOrBuilder>
        getServerListOrBuilderList();
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    ServerDataOrBuilder getServerListOrBuilder(
            int index);
  }
  /**
   * <pre>
   * 服务器列表
   * </pre>
   *
   * Protobuf type {@code proto.ServerListData}
   */
  public  static final class ServerListData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ServerListData)
      ServerListDataOrBuilder {
    // Use ServerListData.newBuilder() to construct.
    private ServerListData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerListData() {
      roles_ = java.util.Collections.emptyList();
      serverList_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServerListData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                roles_ = new java.util.ArrayList<RoleData>();
                mutable_bitField0_ |= 0x00000001;
              }
              roles_.add(
                  input.readMessage(RoleData.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                serverList_ = new java.util.ArrayList<ServerData>();
                mutable_bitField0_ |= 0x00000002;
              }
              serverList_.add(
                  input.readMessage(ServerData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          roles_ = java.util.Collections.unmodifiableList(roles_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          serverList_ = java.util.Collections.unmodifiableList(serverList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResServerList.internal_static_proto_ServerListData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResServerList.internal_static_proto_ServerListData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerListData.class, Builder.class);
    }

    public static final int ROLES_FIELD_NUMBER = 1;
    private java.util.List<RoleData> roles_;
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    public java.util.List<RoleData> getRolesList() {
      return roles_;
    }
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    public java.util.List<? extends RoleDataOrBuilder>
        getRolesOrBuilderList() {
      return roles_;
    }
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    public RoleData getRoles(int index) {
      return roles_.get(index);
    }
    /**
     * <code>repeated .proto.RoleData roles = 1;</code>
     */
    public RoleDataOrBuilder getRolesOrBuilder(
        int index) {
      return roles_.get(index);
    }

    public static final int SERVERLIST_FIELD_NUMBER = 2;
    private java.util.List<ServerData> serverList_;
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    public java.util.List<ServerData> getServerListList() {
      return serverList_;
    }
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    public java.util.List<? extends ServerDataOrBuilder>
        getServerListOrBuilderList() {
      return serverList_;
    }
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    public int getServerListCount() {
      return serverList_.size();
    }
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    public ServerData getServerList(int index) {
      return serverList_.get(index);
    }
    /**
     * <code>repeated .proto.ServerData serverList = 2;</code>
     */
    public ServerDataOrBuilder getServerListOrBuilder(
        int index) {
      return serverList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < roles_.size(); i++) {
        output.writeMessage(1, roles_.get(i));
      }
      for (int i = 0; i < serverList_.size(); i++) {
        output.writeMessage(2, serverList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < roles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, roles_.get(i));
      }
      for (int i = 0; i < serverList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, serverList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServerListData)) {
        return super.equals(obj);
      }
      ServerListData other = (ServerListData) obj;

      boolean result = true;
      result = result && getRolesList()
          .equals(other.getRolesList());
      result = result && getServerListList()
          .equals(other.getServerListList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRolesCount() > 0) {
        hash = (37 * hash) + ROLES_FIELD_NUMBER;
        hash = (53 * hash) + getRolesList().hashCode();
      }
      if (getServerListCount() > 0) {
        hash = (37 * hash) + SERVERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getServerListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServerListData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerListData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerListData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerListData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerListData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerListData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerListData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerListData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerListData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServerListData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerListData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerListData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServerListData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 服务器列表
     * </pre>
     *
     * Protobuf type {@code proto.ServerListData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ServerListData)
        ServerListDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResServerList.internal_static_proto_ServerListData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResServerList.internal_static_proto_ServerListData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerListData.class, Builder.class);
      }

      // Construct using com.insping.libra.proto.ResServerList.ServerListData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRolesFieldBuilder();
          getServerListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (rolesBuilder_ == null) {
          roles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rolesBuilder_.clear();
        }
        if (serverListBuilder_ == null) {
          serverList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          serverListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResServerList.internal_static_proto_ServerListData_descriptor;
      }

      public ServerListData getDefaultInstanceForType() {
        return ServerListData.getDefaultInstance();
      }

      public ServerListData build() {
        ServerListData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerListData buildPartial() {
        ServerListData result = new ServerListData(this);
        int from_bitField0_ = bitField0_;
        if (rolesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            roles_ = java.util.Collections.unmodifiableList(roles_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.roles_ = roles_;
        } else {
          result.roles_ = rolesBuilder_.build();
        }
        if (serverListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            serverList_ = java.util.Collections.unmodifiableList(serverList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.serverList_ = serverList_;
        } else {
          result.serverList_ = serverListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerListData) {
          return mergeFrom((ServerListData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerListData other) {
        if (other == ServerListData.getDefaultInstance()) return this;
        if (rolesBuilder_ == null) {
          if (!other.roles_.isEmpty()) {
            if (roles_.isEmpty()) {
              roles_ = other.roles_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRolesIsMutable();
              roles_.addAll(other.roles_);
            }
            onChanged();
          }
        } else {
          if (!other.roles_.isEmpty()) {
            if (rolesBuilder_.isEmpty()) {
              rolesBuilder_.dispose();
              rolesBuilder_ = null;
              roles_ = other.roles_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rolesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRolesFieldBuilder() : null;
            } else {
              rolesBuilder_.addAllMessages(other.roles_);
            }
          }
        }
        if (serverListBuilder_ == null) {
          if (!other.serverList_.isEmpty()) {
            if (serverList_.isEmpty()) {
              serverList_ = other.serverList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureServerListIsMutable();
              serverList_.addAll(other.serverList_);
            }
            onChanged();
          }
        } else {
          if (!other.serverList_.isEmpty()) {
            if (serverListBuilder_.isEmpty()) {
              serverListBuilder_.dispose();
              serverListBuilder_ = null;
              serverList_ = other.serverList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              serverListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getServerListFieldBuilder() : null;
            } else {
              serverListBuilder_.addAllMessages(other.serverList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerListData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerListData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<RoleData> roles_ =
        java.util.Collections.emptyList();
      private void ensureRolesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          roles_ = new java.util.ArrayList<RoleData>(roles_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          RoleData, RoleData.Builder, RoleDataOrBuilder> rolesBuilder_;

      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public java.util.List<RoleData> getRolesList() {
        if (rolesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(roles_);
        } else {
          return rolesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public int getRolesCount() {
        if (rolesBuilder_ == null) {
          return roles_.size();
        } else {
          return rolesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public RoleData getRoles(int index) {
        if (rolesBuilder_ == null) {
          return roles_.get(index);
        } else {
          return rolesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder setRoles(
          int index, RoleData value) {
        if (rolesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRolesIsMutable();
          roles_.set(index, value);
          onChanged();
        } else {
          rolesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder setRoles(
          int index, RoleData.Builder builderForValue) {
        if (rolesBuilder_ == null) {
          ensureRolesIsMutable();
          roles_.set(index, builderForValue.build());
          onChanged();
        } else {
          rolesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder addRoles(RoleData value) {
        if (rolesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRolesIsMutable();
          roles_.add(value);
          onChanged();
        } else {
          rolesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder addRoles(
          int index, RoleData value) {
        if (rolesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRolesIsMutable();
          roles_.add(index, value);
          onChanged();
        } else {
          rolesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder addRoles(
          RoleData.Builder builderForValue) {
        if (rolesBuilder_ == null) {
          ensureRolesIsMutable();
          roles_.add(builderForValue.build());
          onChanged();
        } else {
          rolesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder addRoles(
          int index, RoleData.Builder builderForValue) {
        if (rolesBuilder_ == null) {
          ensureRolesIsMutable();
          roles_.add(index, builderForValue.build());
          onChanged();
        } else {
          rolesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder addAllRoles(
          Iterable<? extends RoleData> values) {
        if (rolesBuilder_ == null) {
          ensureRolesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, roles_);
          onChanged();
        } else {
          rolesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder clearRoles() {
        if (rolesBuilder_ == null) {
          roles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rolesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public Builder removeRoles(int index) {
        if (rolesBuilder_ == null) {
          ensureRolesIsMutable();
          roles_.remove(index);
          onChanged();
        } else {
          rolesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public RoleData.Builder getRolesBuilder(
          int index) {
        return getRolesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public RoleDataOrBuilder getRolesOrBuilder(
          int index) {
        if (rolesBuilder_ == null) {
          return roles_.get(index);  } else {
          return rolesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public java.util.List<? extends RoleDataOrBuilder>
           getRolesOrBuilderList() {
        if (rolesBuilder_ != null) {
          return rolesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(roles_);
        }
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public RoleData.Builder addRolesBuilder() {
        return getRolesFieldBuilder().addBuilder(
            RoleData.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public RoleData.Builder addRolesBuilder(
          int index) {
        return getRolesFieldBuilder().addBuilder(
            index, RoleData.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RoleData roles = 1;</code>
       */
      public java.util.List<RoleData.Builder>
           getRolesBuilderList() {
        return getRolesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          RoleData, RoleData.Builder, RoleDataOrBuilder>
          getRolesFieldBuilder() {
        if (rolesBuilder_ == null) {
          rolesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              RoleData, RoleData.Builder, RoleDataOrBuilder>(
                  roles_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          roles_ = null;
        }
        return rolesBuilder_;
      }

      private java.util.List<ServerData> serverList_ =
        java.util.Collections.emptyList();
      private void ensureServerListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          serverList_ = new java.util.ArrayList<ServerData>(serverList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ServerData, ServerData.Builder, ServerDataOrBuilder> serverListBuilder_;

      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public java.util.List<ServerData> getServerListList() {
        if (serverListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(serverList_);
        } else {
          return serverListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public int getServerListCount() {
        if (serverListBuilder_ == null) {
          return serverList_.size();
        } else {
          return serverListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public ServerData getServerList(int index) {
        if (serverListBuilder_ == null) {
          return serverList_.get(index);
        } else {
          return serverListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder setServerList(
          int index, ServerData value) {
        if (serverListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerListIsMutable();
          serverList_.set(index, value);
          onChanged();
        } else {
          serverListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder setServerList(
          int index, ServerData.Builder builderForValue) {
        if (serverListBuilder_ == null) {
          ensureServerListIsMutable();
          serverList_.set(index, builderForValue.build());
          onChanged();
        } else {
          serverListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder addServerList(ServerData value) {
        if (serverListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerListIsMutable();
          serverList_.add(value);
          onChanged();
        } else {
          serverListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder addServerList(
          int index, ServerData value) {
        if (serverListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServerListIsMutable();
          serverList_.add(index, value);
          onChanged();
        } else {
          serverListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder addServerList(
          ServerData.Builder builderForValue) {
        if (serverListBuilder_ == null) {
          ensureServerListIsMutable();
          serverList_.add(builderForValue.build());
          onChanged();
        } else {
          serverListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder addServerList(
          int index, ServerData.Builder builderForValue) {
        if (serverListBuilder_ == null) {
          ensureServerListIsMutable();
          serverList_.add(index, builderForValue.build());
          onChanged();
        } else {
          serverListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder addAllServerList(
          Iterable<? extends ServerData> values) {
        if (serverListBuilder_ == null) {
          ensureServerListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, serverList_);
          onChanged();
        } else {
          serverListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder clearServerList() {
        if (serverListBuilder_ == null) {
          serverList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          serverListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public Builder removeServerList(int index) {
        if (serverListBuilder_ == null) {
          ensureServerListIsMutable();
          serverList_.remove(index);
          onChanged();
        } else {
          serverListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public ServerData.Builder getServerListBuilder(
          int index) {
        return getServerListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public ServerDataOrBuilder getServerListOrBuilder(
          int index) {
        if (serverListBuilder_ == null) {
          return serverList_.get(index);  } else {
          return serverListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public java.util.List<? extends ServerDataOrBuilder>
           getServerListOrBuilderList() {
        if (serverListBuilder_ != null) {
          return serverListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(serverList_);
        }
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public ServerData.Builder addServerListBuilder() {
        return getServerListFieldBuilder().addBuilder(
            ServerData.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public ServerData.Builder addServerListBuilder(
          int index) {
        return getServerListFieldBuilder().addBuilder(
            index, ServerData.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ServerData serverList = 2;</code>
       */
      public java.util.List<ServerData.Builder>
           getServerListBuilderList() {
        return getServerListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ServerData, ServerData.Builder, ServerDataOrBuilder>
          getServerListFieldBuilder() {
        if (serverListBuilder_ == null) {
          serverListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ServerData, ServerData.Builder, ServerDataOrBuilder>(
                  serverList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          serverList_ = null;
        }
        return serverListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ServerListData)
    }

    // @@protoc_insertion_point(class_scope:proto.ServerListData)
    private static final ServerListData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerListData();
    }

    public static ServerListData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerListData>
        PARSER = new com.google.protobuf.AbstractParser<ServerListData>() {
      public ServerListData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerListData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerListData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServerListData> getParserForType() {
      return PARSER;
    }

    public ServerListData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoleDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RoleData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string roleName = 1;</code>
     */
    String getRoleName();
    /**
     * <code>string roleName = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoleNameBytes();

    /**
     * <code>int32 roleLevel = 2;</code>
     */
    int getRoleLevel();

    /**
     * <code>string roleData = 3;</code>
     */
    String getRoleData();
    /**
     * <code>string roleData = 3;</code>
     */
    com.google.protobuf.ByteString
        getRoleDataBytes();

    /**
     * <code>int32 roleServerID = 4;</code>
     */
    int getRoleServerID();
  }
  /**
   * Protobuf type {@code proto.RoleData}
   */
  public  static final class RoleData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.RoleData)
      RoleDataOrBuilder {
    // Use RoleData.newBuilder() to construct.
    private RoleData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleData() {
      roleName_ = "";
      roleLevel_ = 0;
      roleData_ = "";
      roleServerID_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoleData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              roleName_ = s;
              break;
            }
            case 16: {

              roleLevel_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              roleData_ = s;
              break;
            }
            case 32: {

              roleServerID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResServerList.internal_static_proto_RoleData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResServerList.internal_static_proto_RoleData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoleData.class, Builder.class);
    }

    public static final int ROLENAME_FIELD_NUMBER = 1;
    private volatile Object roleName_;
    /**
     * <code>string roleName = 1;</code>
     */
    public String getRoleName() {
      Object ref = roleName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roleName_ = s;
        return s;
      }
    }
    /**
     * <code>string roleName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoleNameBytes() {
      Object ref = roleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLELEVEL_FIELD_NUMBER = 2;
    private int roleLevel_;
    /**
     * <code>int32 roleLevel = 2;</code>
     */
    public int getRoleLevel() {
      return roleLevel_;
    }

    public static final int ROLEDATA_FIELD_NUMBER = 3;
    private volatile Object roleData_;
    /**
     * <code>string roleData = 3;</code>
     */
    public String getRoleData() {
      Object ref = roleData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roleData_ = s;
        return s;
      }
    }
    /**
     * <code>string roleData = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRoleDataBytes() {
      Object ref = roleData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roleData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROLESERVERID_FIELD_NUMBER = 4;
    private int roleServerID_;
    /**
     * <code>int32 roleServerID = 4;</code>
     */
    public int getRoleServerID() {
      return roleServerID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRoleNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roleName_);
      }
      if (roleLevel_ != 0) {
        output.writeInt32(2, roleLevel_);
      }
      if (!getRoleDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roleData_);
      }
      if (roleServerID_ != 0) {
        output.writeInt32(4, roleServerID_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRoleNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roleName_);
      }
      if (roleLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roleLevel_);
      }
      if (!getRoleDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roleData_);
      }
      if (roleServerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, roleServerID_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RoleData)) {
        return super.equals(obj);
      }
      RoleData other = (RoleData) obj;

      boolean result = true;
      result = result && getRoleName()
          .equals(other.getRoleName());
      result = result && (getRoleLevel()
          == other.getRoleLevel());
      result = result && getRoleData()
          .equals(other.getRoleData());
      result = result && (getRoleServerID()
          == other.getRoleServerID());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getRoleName().hashCode();
      hash = (37 * hash) + ROLELEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getRoleLevel();
      hash = (37 * hash) + ROLEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRoleData().hashCode();
      hash = (37 * hash) + ROLESERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getRoleServerID();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RoleData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoleData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RoleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RoleData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RoleData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RoleData)
        RoleDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResServerList.internal_static_proto_RoleData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResServerList.internal_static_proto_RoleData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoleData.class, Builder.class);
      }

      // Construct using com.insping.libra.proto.ResServerList.RoleData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roleName_ = "";

        roleLevel_ = 0;

        roleData_ = "";

        roleServerID_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResServerList.internal_static_proto_RoleData_descriptor;
      }

      public RoleData getDefaultInstanceForType() {
        return RoleData.getDefaultInstance();
      }

      public RoleData build() {
        RoleData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RoleData buildPartial() {
        RoleData result = new RoleData(this);
        result.roleName_ = roleName_;
        result.roleLevel_ = roleLevel_;
        result.roleData_ = roleData_;
        result.roleServerID_ = roleServerID_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RoleData) {
          return mergeFrom((RoleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RoleData other) {
        if (other == RoleData.getDefaultInstance()) return this;
        if (!other.getRoleName().isEmpty()) {
          roleName_ = other.roleName_;
          onChanged();
        }
        if (other.getRoleLevel() != 0) {
          setRoleLevel(other.getRoleLevel());
        }
        if (!other.getRoleData().isEmpty()) {
          roleData_ = other.roleData_;
          onChanged();
        }
        if (other.getRoleServerID() != 0) {
          setRoleServerID(other.getRoleServerID());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RoleData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RoleData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object roleName_ = "";
      /**
       * <code>string roleName = 1;</code>
       */
      public String getRoleName() {
        Object ref = roleName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roleName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string roleName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoleNameBytes() {
        Object ref = roleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roleName = 1;</code>
       */
      public Builder setRoleName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roleName = 1;</code>
       */
      public Builder clearRoleName() {
        
        roleName_ = getDefaultInstance().getRoleName();
        onChanged();
        return this;
      }
      /**
       * <code>string roleName = 1;</code>
       */
      public Builder setRoleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roleName_ = value;
        onChanged();
        return this;
      }

      private int roleLevel_ ;
      /**
       * <code>int32 roleLevel = 2;</code>
       */
      public int getRoleLevel() {
        return roleLevel_;
      }
      /**
       * <code>int32 roleLevel = 2;</code>
       */
      public Builder setRoleLevel(int value) {
        
        roleLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 roleLevel = 2;</code>
       */
      public Builder clearRoleLevel() {
        
        roleLevel_ = 0;
        onChanged();
        return this;
      }

      private Object roleData_ = "";
      /**
       * <code>string roleData = 3;</code>
       */
      public String getRoleData() {
        Object ref = roleData_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roleData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string roleData = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRoleDataBytes() {
        Object ref = roleData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roleData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string roleData = 3;</code>
       */
      public Builder setRoleData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roleData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string roleData = 3;</code>
       */
      public Builder clearRoleData() {
        
        roleData_ = getDefaultInstance().getRoleData();
        onChanged();
        return this;
      }
      /**
       * <code>string roleData = 3;</code>
       */
      public Builder setRoleDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roleData_ = value;
        onChanged();
        return this;
      }

      private int roleServerID_ ;
      /**
       * <code>int32 roleServerID = 4;</code>
       */
      public int getRoleServerID() {
        return roleServerID_;
      }
      /**
       * <code>int32 roleServerID = 4;</code>
       */
      public Builder setRoleServerID(int value) {
        
        roleServerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 roleServerID = 4;</code>
       */
      public Builder clearRoleServerID() {
        
        roleServerID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.RoleData)
    }

    // @@protoc_insertion_point(class_scope:proto.RoleData)
    private static final RoleData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoleData();
    }

    public static RoleData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleData>
        PARSER = new com.google.protobuf.AbstractParser<RoleData>() {
      public RoleData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoleData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RoleData> getParserForType() {
      return PARSER;
    }

    public RoleData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ServerData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 serverID = 1;</code>
     */
    int getServerID();

    /**
     * <code>int32 serverType = 2;</code>
     */
    int getServerType();

    /**
     * <code>string serverName = 3;</code>
     */
    String getServerName();
    /**
     * <code>string serverName = 3;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <code>int32 serverStatus = 4;</code>
     */
    int getServerStatus();

    /**
     * <code>string serverDesc = 5;</code>
     */
    String getServerDesc();
    /**
     * <code>string serverDesc = 5;</code>
     */
    com.google.protobuf.ByteString
        getServerDescBytes();
  }
  /**
   * Protobuf type {@code proto.ServerData}
   */
  public  static final class ServerData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ServerData)
      ServerDataOrBuilder {
    // Use ServerData.newBuilder() to construct.
    private ServerData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerData() {
      serverID_ = 0;
      serverType_ = 0;
      serverName_ = "";
      serverStatus_ = 0;
      serverDesc_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServerData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverID_ = input.readInt32();
              break;
            }
            case 16: {

              serverType_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              serverName_ = s;
              break;
            }
            case 32: {

              serverStatus_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              serverDesc_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResServerList.internal_static_proto_ServerData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResServerList.internal_static_proto_ServerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerData.class, Builder.class);
    }

    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverID_;
    /**
     * <code>int32 serverID = 1;</code>
     */
    public int getServerID() {
      return serverID_;
    }

    public static final int SERVERTYPE_FIELD_NUMBER = 2;
    private int serverType_;
    /**
     * <code>int32 serverType = 2;</code>
     */
    public int getServerType() {
      return serverType_;
    }

    public static final int SERVERNAME_FIELD_NUMBER = 3;
    private volatile Object serverName_;
    /**
     * <code>string serverName = 3;</code>
     */
    public String getServerName() {
      Object ref = serverName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      }
    }
    /**
     * <code>string serverName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERSTATUS_FIELD_NUMBER = 4;
    private int serverStatus_;
    /**
     * <code>int32 serverStatus = 4;</code>
     */
    public int getServerStatus() {
      return serverStatus_;
    }

    public static final int SERVERDESC_FIELD_NUMBER = 5;
    private volatile Object serverDesc_;
    /**
     * <code>string serverDesc = 5;</code>
     */
    public String getServerDesc() {
      Object ref = serverDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string serverDesc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServerDescBytes() {
      Object ref = serverDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverID_ != 0) {
        output.writeInt32(1, serverID_);
      }
      if (serverType_ != 0) {
        output.writeInt32(2, serverType_);
      }
      if (!getServerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverName_);
      }
      if (serverStatus_ != 0) {
        output.writeInt32(4, serverStatus_);
      }
      if (!getServerDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serverDesc_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverID_);
      }
      if (serverType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverType_);
      }
      if (!getServerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverName_);
      }
      if (serverStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, serverStatus_);
      }
      if (!getServerDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serverDesc_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServerData)) {
        return super.equals(obj);
      }
      ServerData other = (ServerData) obj;

      boolean result = true;
      result = result && (getServerID()
          == other.getServerID());
      result = result && (getServerType()
          == other.getServerType());
      result = result && getServerName()
          .equals(other.getServerName());
      result = result && (getServerStatus()
          == other.getServerStatus());
      result = result && getServerDesc()
          .equals(other.getServerDesc());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerID();
      hash = (37 * hash) + SERVERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getServerType();
      hash = (37 * hash) + SERVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getServerName().hashCode();
      hash = (37 * hash) + SERVERSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getServerStatus();
      hash = (37 * hash) + SERVERDESC_FIELD_NUMBER;
      hash = (53 * hash) + getServerDesc().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServerData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServerData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ServerData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ServerData)
        ServerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResServerList.internal_static_proto_ServerData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResServerList.internal_static_proto_ServerData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerData.class, Builder.class);
      }

      // Construct using com.insping.libra.proto.ResServerList.ServerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverID_ = 0;

        serverType_ = 0;

        serverName_ = "";

        serverStatus_ = 0;

        serverDesc_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResServerList.internal_static_proto_ServerData_descriptor;
      }

      public ServerData getDefaultInstanceForType() {
        return ServerData.getDefaultInstance();
      }

      public ServerData build() {
        ServerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServerData buildPartial() {
        ServerData result = new ServerData(this);
        result.serverID_ = serverID_;
        result.serverType_ = serverType_;
        result.serverName_ = serverName_;
        result.serverStatus_ = serverStatus_;
        result.serverDesc_ = serverDesc_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerData) {
          return mergeFrom((ServerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerData other) {
        if (other == ServerData.getDefaultInstance()) return this;
        if (other.getServerID() != 0) {
          setServerID(other.getServerID());
        }
        if (other.getServerType() != 0) {
          setServerType(other.getServerType());
        }
        if (!other.getServerName().isEmpty()) {
          serverName_ = other.serverName_;
          onChanged();
        }
        if (other.getServerStatus() != 0) {
          setServerStatus(other.getServerStatus());
        }
        if (!other.getServerDesc().isEmpty()) {
          serverDesc_ = other.serverDesc_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverID_ ;
      /**
       * <code>int32 serverID = 1;</code>
       */
      public int getServerID() {
        return serverID_;
      }
      /**
       * <code>int32 serverID = 1;</code>
       */
      public Builder setServerID(int value) {
        
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverID = 1;</code>
       */
      public Builder clearServerID() {
        
        serverID_ = 0;
        onChanged();
        return this;
      }

      private int serverType_ ;
      /**
       * <code>int32 serverType = 2;</code>
       */
      public int getServerType() {
        return serverType_;
      }
      /**
       * <code>int32 serverType = 2;</code>
       */
      public Builder setServerType(int value) {
        
        serverType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverType = 2;</code>
       */
      public Builder clearServerType() {
        
        serverType_ = 0;
        onChanged();
        return this;
      }

      private Object serverName_ = "";
      /**
       * <code>string serverName = 3;</code>
       */
      public String getServerName() {
        Object ref = serverName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverName = 3;</code>
       */
      public Builder setServerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverName = 3;</code>
       */
      public Builder clearServerName() {
        
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>string serverName = 3;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverName_ = value;
        onChanged();
        return this;
      }

      private int serverStatus_ ;
      /**
       * <code>int32 serverStatus = 4;</code>
       */
      public int getServerStatus() {
        return serverStatus_;
      }
      /**
       * <code>int32 serverStatus = 4;</code>
       */
      public Builder setServerStatus(int value) {
        
        serverStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverStatus = 4;</code>
       */
      public Builder clearServerStatus() {
        
        serverStatus_ = 0;
        onChanged();
        return this;
      }

      private Object serverDesc_ = "";
      /**
       * <code>string serverDesc = 5;</code>
       */
      public String getServerDesc() {
        Object ref = serverDesc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverDesc = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServerDescBytes() {
        Object ref = serverDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverDesc = 5;</code>
       */
      public Builder setServerDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverDesc = 5;</code>
       */
      public Builder clearServerDesc() {
        
        serverDesc_ = getDefaultInstance().getServerDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string serverDesc = 5;</code>
       */
      public Builder setServerDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverDesc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ServerData)
    }

    // @@protoc_insertion_point(class_scope:proto.ServerData)
    private static final ServerData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerData();
    }

    public static ServerData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerData>
        PARSER = new com.google.protobuf.AbstractParser<ServerData>() {
      public ServerData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServerData> getParserForType() {
      return PARSER;
    }

    public ServerData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ServerListData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ServerListData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RoleData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RoleData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ServerData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ServerData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034protos/res_server_list.proto\022\005proto\"W\n" +
      "\016ServerListData\022\036\n\005roles\030\001 \003(\0132\017.proto.R" +
      "oleData\022%\n\nserverList\030\002 \003(\0132\021.proto.Serv" +
      "erData\"W\n\010RoleData\022\020\n\010roleName\030\001 \001(\t\022\021\n\t" +
      "roleLevel\030\002 \001(\005\022\020\n\010roleData\030\003 \001(\t\022\024\n\014rol" +
      "eServerID\030\004 \001(\005\"p\n\nServerData\022\020\n\010serverI" +
      "D\030\001 \001(\005\022\022\n\nserverType\030\002 \001(\005\022\022\n\nserverNam" +
      "e\030\003 \001(\t\022\024\n\014serverStatus\030\004 \001(\005\022\022\n\nserverD" +
      "esc\030\005 \001(\tB<\n\027com.insping.libra.protoB\rRe" +
      "sServerList\252\002\021LibraClient.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ServerListData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ServerListData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ServerListData_descriptor,
        new String[] { "Roles", "ServerList", });
    internal_static_proto_RoleData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_RoleData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RoleData_descriptor,
        new String[] { "RoleName", "RoleLevel", "RoleData", "RoleServerID", });
    internal_static_proto_ServerData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ServerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ServerData_descriptor,
        new String[] { "ServerID", "ServerType", "ServerName", "ServerStatus", "ServerDesc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
